package ER;

import java.io.Serializable;
import java.util.Iterator;
import java.util.Map.Entry;

/**
 * The Physican class has all the access to the Patient Manage System.
 * 
 * @author Z.LU, L.CHEN, T.TRUONG, G.GUERRA.
 */
public class Physician implements Serializable {

	/**
	 * This UID was generated by Eclipse.
	 */
	private static final long serialVersionUID = 4645430800421324105L;

	/**
	 * The looked up Patient.
	 */
	private Patient patient;
	/**
	 * The Patients' data base.
	 */
	protected App patientdata;

	/**
	 * Constructs a Nurse.
	 */
	public Physician() {
		this.setPatient(new Patient());
	}

	/**
	 * Looks up Patient's information by its health card number.
	 * 
	 * @param healthcardnum
	 *            The health card number of the Patient.
	 */
	public void searchPatient(String healthcardnum) {
		this.setPatient(getPatientdata().lookup(healthcardnum));
	}

	/**
	 * Returns The looked up Patient's general information.
	 * 
	 * @return The general information of the looked up Patient
	 */
	public String viewPatient() {
		String pres = "";
		if (!this.getPatient().getPrescription().isEmpty()) {
			Iterator<Entry<String, String>> iter = this.getPatient()
					.getPrescription().entrySet().iterator();
			while (iter.hasNext()) {
				Entry<String, String> entry = iter.next();
				pres = pres + "   time:" + entry.getKey() + "  value:"
						+ entry.getValue() + "\n";
			}
		}
		return "Name: " + this.getPatient().getName() + "\n"
				+ "Date of birth: " + this.getPatient().getBirthDate() + "\n"
				+ "Health card number: "
				+ String.valueOf(this.getPatient().getHealthCardNum())
				+ "\nPrescription history:\n" + pres;
	}

	/**
	 * Returns the patients' data base.
	 * 
	 * @return The data base of patients.
	 */
	public App getPatientdata() {
		return this.patientdata;
	}

	/**
	 * Sets the patients' data base with patientdata.
	 */
	public void setPatientdata(App patientdata) {
		this.patientdata = patientdata;
	}

	/**
	 * Returns the looked up Patient.
	 * 
	 * @return The looked up Patient.
	 */
	public Patient getPatient() {
		return patient;
	}

	/**
	 * Sets the looked up Patient.
	 */
	public void setPatient(Patient patient) {
		this.patient = patient;
	}
}